# Generated by Django 6.0.5 on 2026-05-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_foods_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='organisation',
            new_name='organization',
        ),
    ]
