# Generated by Django 6.0.5 on 2026-05-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_organisation_order_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='overall_price',
            new_name='total',
        ),
    ]
