version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: parvoz_db
      POSTGRES_USER: parvoz_user
      POSTGRES_PASSWORD: Alabas23
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parvoz_user -d parvoz_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createcachetable django_cache_table &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/parvoz
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  postgres_data: